name: Release

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      version: ${{ steps.release.outputs.version }}
    steps:
      - uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5
        id: release

  upload-assets:
    needs: release-please
    if: needs.release-please.outputs.release_created
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: npm run build
        
      - name: Create tarball
        run: tar -czf app-templates-${{ needs.release-please.outputs.version }}.tar.gz -C layers .

      - name: Upload release asset
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release upload ${{ needs.release-please.outputs.tag_name }} app-templates-${{ needs.release-please.outputs.version }}.tar.gz
